version: '3.9'

services:
  zookeeper:
    container_name: coffee_zookeeper_dev
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: coffee_kafka_dev
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: coffee_zookeeper_dev:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://coffee_kafka_dev:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  product-service:
    container_name: product_service_dev
    build: ./services/product-service
    ports:
      - "1337:1337"
    env_file:
      - ./services/product-service/config/.env.development
    environment:
      KAFKAJS_NO_PARTITIONER_WARNING: "1"
      NODE_ENV: development
    depends_on:
      - kafka
      - product-db

  product-db:
    image: mongo:7
    container_name: product_db_dev
    ports:
      - "27107:27108"
    volumes:
      - product-db-data:/data/db

  order-service:
    container_name: order-service_dev
    build: ./services/order-service
    ports:
      - "1338:1338"
    env_file:
      - ./services/order-service/config/.env.development
    environment:
      KAFKAJS_NO_PARTITIONER_WARNING: "1"
      NODE_ENV: development

    depends_on:
      - kafka
      - order-db
  order-db:
    container_name: order-db_dev
    image: mongo:7
    ports:
      - "27108:27109"
    volumes:
      - order-db-data:/data/db

volumes:
  product-db-data:
  order-db-data:
