version: '3.9'

services:
  zookeeper:
    container_name: coffee_zookeeper
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: coffee_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: coffee_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://coffee_kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  product-service:
    container_name: product_service
    build: ./services/product-service
    ports:
      - "3001:3000"
    env_file:
      - ./services/product-service/config/.env.production
    environment:
      KAFKAJS_NO_PARTITIONER_WARNING: "1"
      NODE_ENV: production
    depends_on:
      - kafka
      - product-db

  product-db:
    image: mongo:7
    container_name: product_db
    ports:
      - "27018:27017"
    volumes:
      - product-db-data:/data/db

  order-service:
    build: ./services/order-service
    ports:
      - "3002:3000"
    env_file:
      - ./services/order-service/.env.production
    environment:
      KAFKAJS_NO_PARTITIONER_WARNING: "1"
      NODE_ENV: production

    depends_on:
      - kafka
      - order-db
  order-db:
    image: mongo:7
    volumes:
      - order-db-data:/data/db

volumes:
  product-db-data:
  order-db-data:
