version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  product-service:
    build: ./services/product-service
    ports:
      - "3001:3000"
    env_file:
      - ./services/product-service/.env
    depends_on:
      - kafka
      - product-db

  product-db:
    image: mongo:7
    volumes:
      - product-db-data:/data/db

  order-service:
    build: ./services/order-service
    ports:
      - "3002:3000"
    env_file:
      - ./services/order-service/.env
    depends_on:
      - kafka
      - order-db

  order-db:
    image: mongo:7
    volumes:
      - order-db-data:/data/db

volumes:
  product-db-data:
  order-db-data:
